StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{60D2F0EA48A5EEA8}" {
   Id "MI3_MenuAccept"
   Target_en_us "Accept"
   Target_de_de "Weiter"
   Modified 1624441019
   Author "Oscar"
   LastChanged "Oscar"
  }
  CustomStringTableItem "{60D2F0EA3F9007B2}" {
   Id "MI3_MenuBack"
   Target_en_us "Back"
   Target_de_de "Zurück"
   Modified 1624441006
   Author "Oscar"
   LastChanged "Oscar"
  }
  CustomStringTableItem "{60D2CD656158493A}" {
   Id "MI3_SaveGame_Delete"
   Target_en_us "Delete"
   Target_de_de "Löschen"
   Modified 1624429709
   Author "Oscar"
   LastChanged "Oscar"
  }
  CustomStringTableItem "{60D2CD64EDF9295D}" {
   Id "MI3_SaveGame_Load"
   Target_en_us "Load"
   Target_de_de "Laden"
   Modified 1624429483
   Author "Oscar"
   LastChanged "Oscar"
  }
 }
}